/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package trabalho1_prj_calculadora;

/**
 *
 * @author Thainá Pavone
 */
public class Interface extends javax.swing.JPanel {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        LabN2 = new javax.swing.JLabel();
        LabN1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        BttSoma = new javax.swing.JButton();
        BttSub = new javax.swing.JButton();
        BttMult = new javax.swing.JButton();
        MultDiv = new javax.swing.JButton();
        LabResult = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        LabN2.setText("N2:");

        LabN1.setText("N1:");

        BttSoma.setText("+");
        BttSoma.addActionListener(this::BttSomaActionPerformed);

        BttSub.setText("-");
        BttSub.addActionListener(this::BttSubActionPerformed);

        BttMult.setText("*");
        BttMult.addActionListener(this::BttMultActionPerformed);

        MultDiv.setText("/");
        MultDiv.addActionListener(this::MultDivActionPerformed);

        LabResult.setText("Resultado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LabN1)
                                .addGap(22, 22, 22)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(LabN2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(BttSoma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BttSub)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BttMult)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MultDiv))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(LabResult)))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabN2)
                    .addComponent(LabN1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BttSoma)
                    .addComponent(BttSub)
                    .addComponent(BttMult)
                    .addComponent(MultDiv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabResult)
                .addContainerGap(113, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BttSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttSomaActionPerformed
                                        
    try {

        double n1 = Double.parseDouble(txt1.getText());
        double n2 = Double.parseDouble(txt2.getText());

        Operacoes op = new Operacoes();
        double resultado = op.soma(n1, n2);

        LabResult.setText("Resultado: " + resultado);

    } catch (Exception e) {

        LabResult.setText("Erro: Digite números!");

    }
    }//GEN-LAST:event_BttSomaActionPerformed

    private void BttSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttSubActionPerformed
            try {

        double n1 = Double.parseDouble(txt1.getText());
        double n2 = Double.parseDouble(txt2.getText());

        Operacoes op = new Operacoes();
        double resultado = op.subtracao(n1, n2);

        LabResult.setText("Resultado: " + resultado);

    } catch (Exception e) {

        LabResult.setText("Erro: Digite números!");

    }
    }//GEN-LAST:event_BttSubActionPerformed

    private void BttMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttMultActionPerformed
            try {

        double n1 = Double.parseDouble(txt1.getText());
        double n2 = Double.parseDouble(txt2.getText());

        Operacoes op = new Operacoes();
        double resultado = op.multiplicacao(n1, n2);

        LabResult.setText("Resultado: " + resultado);

    } catch (Exception e) {

        LabResult.setText("Erro: Digite números!");

    }
    }//GEN-LAST:event_BttMultActionPerformed

    private void MultDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultDivActionPerformed
        try {
            double n1 = Double.parseDouble(txt1.getText());
            double n2 = Double.parseDouble(txt2.getText());
            
            if (n2 == 0) {
                LabResult.setText("Erro: Divisão por zero!");
            } else {
                Operacoes op = new Operacoes();
                double resultado = op.divisao(n1, n2);
                LabResult.setText("Resultado: " + resultado);
            }
        } catch (Exception e) {
            LabResult.setText("Erro: Digite números!");
        }
    }                                       

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            javax.swing.JFrame frame = new javax.swing.JFrame("Calculadora");
            frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
            frame.setContentPane(new Interface());
            frame.pack();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        });
    }//GEN-LAST:event_MultDivActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BttMult;
    private javax.swing.JButton BttSoma;
    private javax.swing.JButton BttSub;
    private javax.swing.JLabel LabN1;
    private javax.swing.JLabel LabN2;
    private javax.swing.JLabel LabResult;
    private javax.swing.JButton MultDiv;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables
}
